### ISSUE TITLE
Support the official constraint template format

### ISSUE THREAD

**Issue by t12g** [forseti-security/config-validator#30]
Currently the `targets` field look like the following:
``` 
targets:
   validation.gcp.forsetisecurity.org:
      rego: |
rego code here
```

It deviates from the constraint framework format. In constraint framework, the `targets` field is a list of maps:

```
targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
rego code here
```

Reference: https://github.com/open-policy-agent/frameworks/tree/master/constraint#what-is-a-constraint-template
